-- PostgreSQL schema for SeinfeldAPI, converted from the SQL Server scripts in this
-- same directory (create_users_table.sql, create_episodes_table.sql,
-- create_episodequotes_table.sql) as part of the SQL Server -> PostgreSQL migration.
-- Applied to its own dedicated "seinfelddb" database on MRTN-PSQL, owned by a
-- dedicated "seinfeld_app" role (separate from Knowledge-Center-API's appdb/appuser).
--
-- IMPORTANT: every identifier is double-quoted to preserve exact PascalCase casing.
-- SeinfeldDbContext (Data/SeinfeldDbContext.cs) is an EF Core code-first model with
-- no naming-convention plugin configured, so the Npgsql provider generates SQL
-- against the C# property names as-is (Id, Title, Username, ...). Unquoted Postgres
-- identifiers fold to lowercase, which would break every one of those mappings.
--
-- IDENTITY columns use GENERATED BY DEFAULT AS IDENTITY (not ALWAYS) so the data
-- restored from the SQL Server .bak can carry over its original explicit IDs.
-- After loading data, reset each sequence, e.g.:
--   SELECT setval(pg_get_serial_sequence('"Episodes"', 'Id'), (SELECT MAX("Id") FROM "Episodes"));

CREATE TABLE "Users" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username" VARCHAR(50) NOT NULL UNIQUE,
    "PasswordHash" VARCHAR(255) NOT NULL,
    "Role" VARCHAR(20) NOT NULL DEFAULT 'User',
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE "Episodes" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" VARCHAR(200) NOT NULL,
    "Season" VARCHAR(10),
    "EpisodeNumber" VARCHAR(10),
    "AirDate" DATE
);

CREATE TABLE "EpisodeQuotes" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EpisodeId" INTEGER NOT NULL,
    "Quote" TEXT NOT NULL,
    "Character" VARCHAR(100) NOT NULL,
    CONSTRAINT "FK_EpisodeQuotes_Episodes" FOREIGN KEY ("EpisodeId") REFERENCES "Episodes" ("Id") ON DELETE CASCADE
);

-- One episode per season + episode number (also in add_episodes_unique_season_episode.sql)
CREATE UNIQUE INDEX "UX_Episodes_Season_EpisodeNumber" ON "Episodes" ("Season", "EpisodeNumber");
